[package]
name = "rsbench"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
lambda_http = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7"
tokio-postgres-rustls = "0.13"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
chrono = "0.4"
url = "2"

[profile.release]
opt-level = "z"
strip = true
lto = true
