(lang dune 3.22)

(name ocaml-lambda-hierarchy)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name ocaml-lambda-hierarchy)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  ocaml
  lambda-runtime
  lambda-runtime-api-gateway
  base
  core
  yojson
  uuidm
  ptime
  eio
  eio_main
  smaws-clients
  (alcotest :with-test)
  (base_quickcheck :with-test)
  (ppx_jane :with-test))
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
