[package]
name = "meter-heartbeat"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "meter-heartbeat"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.13"
aws_lambda_events = { workspace = true, features = ["kinesis"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
aws-config.workspace = true
aws-sdk-firehose = "1"
anyhow.workspace = true
